baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Saioa Manzano-Morales
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv/
          weight: 5 
        - name: Publications
          url: publications/
          weight: 5 
        - name: Outreach
          url: outreach/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3

params:
    description: "This website hosts Saioa Manzano-Morales's research papers, course materials, data, curriculum vitae, and contact information."
    author: Saioa Manzano-Morales
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["cv", "publications", "outreach","courses"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Saioa Manzano-Morales
          subtitle: "I am a PhD Candidate in the Comparative Genomics Group at the Barcelona Supercomputing Center, led by Toni Gabaldón.  My research centers on early eukaryotic evolution, with a particular focus on Asgard archaea."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: cv/
            - name: Publications
              url: publications/
            - name: Outreach
              url: outreach/
            - name: Projects
              url: projects/
            - name: Courses
              url: courses/

    socialIcons:
        - name: CV
          url: docs/cv/cv.pdf
        - name: Email
          url: mailto:saioa.manzano@bsc.es
        - name: Google Scholar
          url: https://scholar.google.es/citations?user=p419EbgAAAAJ&hl=es
        - name: GitHub
          url: https://github.com/saimanzano
        - name: Bluesky
          url: https://bsky.app/profile/microbiobits.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Saioa Manzano-Morales"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
